application: aqquadro-hrd
version: go1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /
  static_files: index.html
  upload: index.html
    
- url: /.*
  script: _go_app